Dockerfile
pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFFhirWebClientProvider.java
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManager.java
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultHandler.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManagerTest.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultCollectorIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultHandlerTest.java

Supports the new feasibility DSF plugin in version `0.2.0`.
Resolves #10

Support New DSF Plugin

---

src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManager.java
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultHandler.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManagerTest.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultCollectorIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultHandlerTest.java

Adds support for the DSF feasibility plugin in
version 0.5.0.

Support DSF Feasibility Plugin v0.5.0

---

pom.xml

- update to the latest minor releases of several libraries
- most notably: spring boot, spring security, keycloak

No issue - update dependencies

---

src/main/java/de/numcodex/feasibility_gui_backend/query/translation/QueryTranslatorSpringConfig.java

updated the system url to match the current codesystem url of consent.

Fixed the codesystem alias for consent.

---

pom.xml

#88 - Handling responses from aktin broker leads to exception

---

pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfig.java
src/main/resources/application.yml
src/main/resources/static/v3/api-docs/swagger.yaml

- update springdoc-openapi to a version compatible with spring boot 3
- update query result endpoints

#57 - Swagger UI is broken

---

.gitignore
src/main/java/de/numcodex/feasibility_gui_backend/query/result/ResultService.java
src/main/resources/logback.xml

- add RollingFileAppender for logback to simply add all added result lines to a file

#76 - Log results to file

---

pom.xml

- update snakeyaml dependency to 2.0

#97 - Update SnakeYaml to v2.0 to resolve CVE-2022-1471

---

pom.xml

- update spring boot to 3.0.5 to fix cve-2023-20860 and cve-2023-20861

#100 - Update Spring Boot to 3.0.5

---

pom.xml

- update spring boot to 3.1.0 to fix https://avd.aquasec.com/nvd/cve-2023-20873

#128 - Fix code scanning alert - Spring Boot Security Bypass with Wildcard Pattern Matching on Cloud Foundry

---

src/main/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfig.java

- adapt HttpSecurity config in WebSecurityConfig.java to new spring security api

#135 - Adapt spring security configuration to newer api

---

src/main/java/de/numcodex/feasibility_gui_backend/query/v2/QueryHandlerRestController.java

- add "Retry-After" to the list of exposed headers in QueryHandlerRestController

#151 - Expose Retry-After header for cross origin requests

---

pom.xml

- Increase version nr in pom.xml

Hotfix 3.1.2

---

src/test/java/de/numcodex/feasibility_gui_backend/query/dispatch/QueryDispatcherIT.java

#172 - Fix code scanning alert - unread local variable

---

Dockerfile

#154 - Add apt autoremove and apt clean to Dockerfile

---

.github/workflows/ci.yml
pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFFhirWebClientProvider.java
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManager.java
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultCollector.java
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultHandler.java
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/FhirWebClientProvider.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManagerTest.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultCollectorIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultHandlerTest.java

- Update DSF BPE 1.0.0 resource definition uri's.
- Use official DSF dependencies. 
- Remove HiGHmed GitHub repository in CI as version 1.0.0 of DSF is published to maven central.

Update DSF Feasibility Task Resource to Version 1.0

---

src/main/java/de/numcodex/feasibility_gui_backend/query/v3/QueryHandlerRestController.java
src/test/java/de/numcodex/feasibility_gui_backend/query/v3/QueryHandlerRestControllerIT.java

- Add check if the user is allowed to retrieve the detailed obfuscated result

#170 - Restrict access to detailed obfuscated results

---

src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java
src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/QueryTemplateRepository.java
src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/SavedQueryRepository.java
src/main/java/de/numcodex/feasibility_gui_backend/query/templates/QueryTemplateHandler.java
src/main/java/de/numcodex/feasibility_gui_backend/query/v3/QueryHandlerRestController.java
src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/templates/QueryTemplateHandlerTest.java
src/test/java/de/numcodex/feasibility_gui_backend/query/v3/QueryHandlerRestControllerIT.java

- add check if a user already has a saved query or query templated stored with the submitted label

#174 - Prevent duplicate names

---

DEVELOPMENT.md

- Add DEVELOPMENT.md file containing release checklist

#164 - Add release checklist

---

src/test/java/de/numcodex/feasibility_gui_backend/common/api/TermCodeTest.java

- add test class for equals and hashcode method on TermCode.java

#184 - Add tests for TermCode

---

src/main/java/de/numcodex/feasibility_gui_backend/query/result/RandomSiteNameGenerator.java

- change RandomSiteNameGenerator from Class to Interface

#185 - Convert RandomSiteNameGenerator to interface

---

Dockerfile
README.md
docker-entrypoint.sh

- add docker-entrypoint.sh script to check for certs
- update dockerfile and readme

#203 - Support self-signed certificates

---

pom.xml

- update spring boot from 3.1.3 to 3.1.5

#227 - Update Spring boot

---

.github/workflows/ci.yml

* Update github actions to newer versions (mostly due to switch from node 16 to node 20).
* Add token for codecov

#254 - Update GitHub actions

---

pom.xml

#262 - Update to spring boot 3.2.3

---

pom.xml

- update testcontainers to 1.19.7 and commons-compress to 1.26.1

#267 - Update testcontainers dependency

---

pom.xml

#262 - Update spring boot to 3.2.4

---

pom.xml

- update spring-boot-starter-oauth2-resource-server 
- update nimbus-jose-jwt lib

#275 - Denial of Service in Connect2id Nimbus JOSE+JWT

---

pom.xml

#279 - Fix code scanning alert - netty-codec-http: Allocation of Resources Without Limits or Throttling

---

pom.xml

#274 - Fix code scanning alert - xnio: StackOverflowException when the chain of notifier states becomes problematically big

---

pom.xml

- update spring boot
- update flyway dependency to postgresql specific

#290 - Update to Spring Boot 3.3.0

---

pom.xml

- update ontology version in pom.xml

#293 - Update Ontology to v2.2.0-RC

---

pom.xml

- update ontology version to v2.2.0 in pom.xml

#299 - Update Ontology to v2.2.0

---

CHANGELOG.md
pom.xml

Only change is the update of the ontology to the release version 2.2.0

Release v5.0.0 rc.1

---

README.md
pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/OAuthClientException.java
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/OAuthInterceptor.java
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectSpringConfig.java
src/main/resources/application.yml
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/OAuthInterceptorIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectSpringConfigIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectSpringConfigTest.java
src/test/resources/de/numcodex/feasibility_gui_backend/query/broker/direct/fhir-metadata.json
src/test/resources/de/numcodex/feasibility_gui_backend/query/broker/direct/realm-test.json
src/test/resources/de/numcodex/feasibility_gui_backend/query/broker/realm-test-short-expiry.json

Use client credentials flow for oauth authentication.
Add new and enhance existing integrations tests to test authentication options.

Add OpenID Connect authentication in direct broker

---

pom.xml

- update spring boot and undertow dependencies

#304 - Fix code scanning alert - undertow

---

pom.xml

Increase spring boot version in pom.xml

#316 - Update Spring Boot to 3.3.2

---

.github/scripts/create-keycloak-user.sh
.github/workflows/ci.yml
Dockerfile

- change addgroup/adduser to groupadd/useradd cmds

#319 - Fix github action error

---

src/main/java/de/numcodex/feasibility_gui_backend/query/dispatch/QueryDispatcher.java

- add the error message to the dispatch failed message in the error log

#280 - Provide useful error message when fhir server is unreachable

---

src/main/resources/application.yml

- add env variable for dbname in datasource url

#325 - Make Database configurable

---

src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptServiceIT.java

- annotate CodeableConceptServiceIT as disabled for now

#333 - Disable CodeableConceptServiceIT for now

---

pom.xml

- update spring boot dependency

#349 - Update to spring boot 3.3.3

---

src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsService.java

- Add a hardcoded mapping from "context" to "context.code" when getting the aggregations to return the filter options

#352 - Context select options not shown in search filters

---

src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsService.java

- add a function score query that boosts all queries with availability > 0 by 100 in score. It does not make a difference if the availability is 10 or 10000, all are boosted by the same fixed value

#367 - Sort unavailable criteria to the bottom

---

pom.xml

#370 - Update fhir-resources dependency

---

pom.xml

#371 - Update spring boot to 3.3.4

---

.github/integration-test/ontology/dse/profile_tree.json
pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/dse/api/DisplayEntry.java
src/main/java/de/numcodex/feasibility_gui_backend/dse/api/DseProfileTreeNode.java
src/main/java/de/numcodex/feasibility_gui_backend/dse/api/LocalizedValue.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/DseServiceTest.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/v4/DseRestControllerIT.java
src/test/resources/ontology/dse/profile_tree.json

- modify DseProfile and Field according to changes in dse profile database entry
- modify DseProfileTreeNode according to changes in profile_tree.json

#380 - Change structure of dse profile_tree and profile details for translations

---

.github/workflows/ci.yml

- add trivy db env variables to ci.yml

#386 - Fix trivy build error

---

src/main/java/de/numcodex/feasibility_gui_backend/dse/api/Field.java
src/main/resources/static/v3/api-docs/swagger.yaml

- Add both fields to Field.java
- fix missing displayEntry in openapi doc

#389 - Add recommended and required to dse field

---

src/main/java/de/numcodex/feasibility_gui_backend/terminology/TerminologyService.java
src/main/java/de/numcodex/feasibility_gui_backend/terminology/validation/StructuredQueryValidation.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/TerminologyServiceTest.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/validation/StructuredQueryValidationTest.java

- remove version from termcode check during query validation
- rename parameter in containsInvalidCriteria method

#391 - Ignore termcode version during query validation

---

src/main/java/de/numcodex/feasibility_gui_backend/dse/api/Field.java

- add "referencedProfiles"  to dse Field class

#398 - Add referencedProfiles string array to dse profile

---

pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsService.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptServiceTest.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsServiceTest.java

Update Spring Boot and make some small changes required by the inherent update of the elasticsearch client

#403 - Update spring boot to 3.4.0

---

CHANGELOG.md
pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManager.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManagerTest.java

Release v6.0.2

---

.github/scripts/download-and-unpack-ontology.sh
.github/workflows/ci.yml
docker-compose.yml
pom.xml

- change download url for ontology files accordingly

#412 - Switch - Ontology - get from assets

---

.github/scripts/download-and-unpack-ontology.sh
.github/workflows/ci.yml
CHANGELOG.md
docker-compose.yml
pom.xml

Change download location for ontology files

Release v6.0.3

---

src/main/java/de/numcodex/feasibility_gui_backend/terminology/validation/StructuredQueryValidation.java

- add missing parameter in log message

#425 - Fix code scanning alert - Unused format argument

---

src/main/java/de/numcodex/feasibility_gui_backend/query/broker/OAuthInterceptor.java
src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingService.java

- replace calls to Bandwith constructor with BandwithBuilder
- replace oauth token request constructor call with call to builder

#424 - Replace deprecated calls to bucket4j library

---

src/test/java/de/numcodex/feasibility_gui_backend/dse/v4/DseRestControllerIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingInterceptorIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/v4/QueryHandlerRestControllerIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/v4/QueryTemplateHandlerRestControllerIT.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsServiceIT.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/v4/CodeableConceptRestControllerIT.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/v4/TerminologyRestControllerIT.java

- replace @MockBean with @MockitoBean

#434 - Replace deprecated MockBeans

---

pom.xml

- update spring boot dependency

#437 - Update to spring boot 3.4.2

---

.github/workflows/ci.yml
docker-compose.yml
pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/terminology/api/AttributeDefinition.java

- update ontology tag to 3.0.2-alpha.2
- modify AttributeDefinition to include displayentry

#430 - Adjust ui profiles to adjust for translations

---

pom.xml

#444 - Upgrade sq2cql to 0.7.0

---

pom.xml

- update sq2cql dependency to 0.8.0-alpha.1

#450 - Update sq2cql to new version - time restriction bugfix

---

src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingService.java

- fix wrong bucket capacity for detailed obfuscated site results

#457 - standort DETAILS buggy

---

src/main/resources/application.yml

- replace deprecated settings to updated ones

#462 - Change management endpoint configuration

---

CHANGELOG.md
pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingErrorAttributes.java
src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingService.java
src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptService.java
src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsService.java
src/main/resources/application.yml

- Management endpoint configuration updated ([#462](https://github.com/medizininformatik-initiative/feasibility-backend/issues/462))
- The search in translations/originals in the ontology was not working as intended ([#455](https://github.com/medizininformatik-initiative/feasibility-backend/issues/455))
- The amount of allowed calls to detailed obfuscated records was not read correctly ([#457](https://github.com/medizininformatik-initiative/feasibility-backend/issues/457))
- Update Spring Boot to 3.4.3

Release v6.1.1

---

pom.xml

Release v6.2.0-alpha

---

pom.xml

- move the plugins out of the profile

#471 - Move maven plugins to create git and build info out of the download ontology profile

---

pom.xml

Alpha release with latest sq2cql and ontology alpha

Release v6.2.0-alpha.1

---

.github/workflows/ci.yml
CHANGELOG.md
pom.xml

Release v6.2.1

---

.github/workflows/ci.yml
CHANGELOG.md
pom.xml

Release v6.2.2

---

pom.xml

- update spring boot dependency

#485 - Update Spring Boot to 3.4.4

---

pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/query/translation/QueryTranslatorSpringConfig.java

- add jackson-datatype-jsr310 dependency
- configure objectmapper to use this module

#488 - Creating dataquery with filterdate causes error

---

.github/workflows/ci.yml
docker-compose.yml
pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/dse/api/DseProfile.java
src/main/java/de/numcodex/feasibility_gui_backend/dse/api/Reference.java
src/main/java/de/numcodex/feasibility_gui_backend/dse/api/ReferencedProfile.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/DseServiceTest.java
src/test/resources/ontology/dse/profile_tree.json

- adapt to the changes made to dse profiles in the ontology generator
- update ontology to 3.5.0
- update spring boot to 3.4.5

#496 - Change DSE profile representation

---

src/main/java/de/numcodex/feasibility_gui_backend/query/api/Dataquery.java
src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/Dataquery.java

- register modules for objectmappers in Dataquery.java

#506 - Error reading query list

---

pom.xml
src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java
src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFSpringConfig.java
src/main/java/de/numcodex/feasibility_gui_backend/query/dataquery/DataqueryHandler.java
src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingService.java
src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingServiceSpringConfig.java
src/main/java/de/numcodex/feasibility_gui_backend/query/result/ResultService.java
src/main/java/de/numcodex/feasibility_gui_backend/query/result/ResultServiceSpringConfig.java
src/main/java/de/numcodex/feasibility_gui_backend/query/v5/FeasibilityQueryHandlerRestController.java
src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingServiceTest.java
src/test/java/de/numcodex/feasibility_gui_backend/query/result/ResultServiceTest.java

- use PeriodDuration class instead of java.time.Duration

#519 - Change duration parser

---

src/main/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfig.java

- replace MvcRequestMatcher with PathPatternRequestMatcher in WebSecurityConfig
- replace requiresChannel with redirectToHttps in WebSecurityConfig

#526 - Replace deprecated spring security methods

---

src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java
src/main/java/de/numcodex/feasibility_gui_backend/query/v5/FeasibilityQueryHandlerRestController.java
src/main/resources/static/v3/api-docs/swagger.yaml
src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceTest.java
src/test/java/de/numcodex/feasibility_gui_backend/query/translation/CqlQueryTranslatorIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/v5/FeasibilityQueryHandlerRestControllerIT.java

- add endpoint that takes a ccdl and translates it to cql

#516 - provide export of CQL "translation"

---

pom.xml

- update spring boot dependency

#534 - Update Spring Boot to 3.5.3

---

Dockerfile
README.md
docker-compose.yml

- add missing env vars
- fix wording
- update temurin base image
- remove unused vars

#542 - Documentation Housekeeping

---

src/main/java/de/numcodex/feasibility_gui_backend/terminology/persistence/Coding.java
src/test/java/de/numcodex/feasibility_gui_backend/common/api/TermCodeTest.java
src/test/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfigIT.java
src/test/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfigSslIT.java
src/test/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfigTest.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/api/DseProfileTest.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/api/DseProfileTreeNodeTest.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/api/FieldDisplayEntryTest.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/api/FieldTest.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/api/FilterTest.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/api/LocalizedValueListTest.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/api/ReferenceTest.java
src/test/java/de/numcodex/feasibility_gui_backend/dse/persistence/DseProfileTest.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/TerminologyServiceTest.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/api/AttributeDefinitionTest.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/api/CriteriaProfileDataTest.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/persistence/CodingTest.java
src/test/java/de/numcodex/feasibility_gui_backend/terminology/validation/StructuredQueryValidationTest.java

- Improve coverage for WebSecurityConfig

#552 - Improve test coverage

---

pom.xml

- Override undertow version to 2.3.19.Final

#641 - Update undertow

---

src/test/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectBrokerClientCqlIT.java
src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFFhirWebClientProviderTest.java

- update blaze version in DirectBrokerClientCqlIT and DSFFhirWebClientProviderTest

#658 - Update blaze testcontainer
