medizininformatik-initiative/feasibility-backend

src/main/resources/application.yml
Allow Keycloak to bypass the Header.Location param. Was necessary after changing the query reply from 200-OK to 201-CREATED.
=> add exposed-headers:Location for Keycloak

Dockerfile, pom.xml, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManager.java, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManagerTest.java
Adds a name attribute to any library resource created
using the DSF client. This fixes issues when using a
HAPI FHIR server that is about to evaluate a measure
referencing such a library.
Fixes #6
=> Add Missing Name Attribute to Library using DSF

.github/workflows/ci.yml, Dockerfile, pom.xml
Resolves #12 
Makes use of new Eclipse Temurin images in both artifacts and CI jobs.
Also updates the Spring version to fix a security vulnerability.
=> Switch to Eclipse Temurin Images

pom.xml, src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java, src/main/java/de/numcodex/feasibility_gui_backend/query/dispatch/QueryDispatchSpringConfig.java, src/main/java/de/numcodex/feasibility_gui_backend/query/dispatch/QueryDispatcher.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v1/QueryHandlerRestController.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v2/QueryHandlerRestController.java, src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/dispatch/QueryDispatcherIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/dispatch/QueryDispatcherTest.java, src/test/java/de/numcodex/feasibility_gui_backend/query/v1/QueryHandlerRestControllerIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/v2/QueryHandlerRestControllerIT.java
Resolves #25.
Allows dispatching queries via brokers in an asynchronous fashion. Dispatch is done on a single thread since transactional database operations are involved. The reason for this is that Spring's transaction propagation has to be respected. Using multiple threads breaks this because transaction information is stored within thread local variables and thus cannot be shared between threads.
The goal for this implementation is that individual brokers can fail without affecting those that ran sucessfully. This gives the UI (or any other client) the possibility to request at least partial results.
A request will only ever fail if all participating brokers fail to publish a query.
=> Asynchronously Dispatch Queries via Brokers

pom.xml, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManager.java, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultHandler.java, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManagerTest.java, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultCollectorIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultHandlerTest.java
Resolves #36 
This PR also bumps Spring to a new bugfix version and takes care of a [CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42889) that allows for RCEs.
The `commons-text` dependency has been replaced in order to tackle the CVE. This is a transitive dependency used by `dsf-fhir-webservice-client`. After talking to the devs it was clear that they cannot bump the version since that would break major parts of the DSF framework. Thus, adjustments have been made in this project (reasoning also added as a comment in `pom.xml`).
=> Support DSF Feasibility Plugin v0.4.0

Dockerfile
We have 64 CVE's with the Focal image. We also don't need to support older Docker infrastructures anymore.
=> Switch to Non Focal Based Docker Image

src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java, src/main/java/de/numcodex/feasibility_gui_backend/query/QueryNotFoundException.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v1/QueryHandlerRestController.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v2/QueryHandlerRestController.java, src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceIT.java
- instead of returning null when the author of a non-existing query is requested, throw an exception
- check for this exception in calling controllers and return 404 in this case
- add test for this case
=> #66 - Fix Potential Bug in QueryHandlerService.getAuthorId Able to Return Null

src/main/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfig.java
- add http.cors() call to WebSecurityConfig to bypass auth checks for OPTIONS requests (according to https://www.baeldung.com/spring-security-cors-preflight#solution )
=> #79 - CORS failing

src/main/java/de/numcodex/feasibility_gui_backend/config/RateLimitingConfig.java, src/main/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfig.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v2/QueryTemplateHandlerRestController.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/TerminologyRestController.java
- move authorization check for terminology and template endpoints to the central WebSecurityConfig instead of using PreAuthorize annotations
- close #82
=> #82 - Security for template and terminology endpoint missing

src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingInterceptor.java, src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingService.java, src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingServiceSpringConfig.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v2/QueryHandlerRestController.java, src/main/resources/application.yml, src/test/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingInterceptorIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingServiceTest.java, src/test/resources/application.yml
- add a second bucket to enforce a quota on the detailed obfuscated results endpoint
- currently, returning a token back to the bucket when the actually received result was only a summary (due to whatever reason...result no longer available, too few sites responded, too few results received) is done in the afterCompletion method of the interceptor. This does however not allow modifying the headers any more. So a custom header is remaining in this case and the remaining requests variable might be 1 too low
=> #68 - limit requesting of detailed results per user

src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryResultHandler.java
- delete measure report from dsf after it was fetched
=> #75 - Delete Feasibility Result from DSF after Consumption

pom.xml
- exclude json dependency from json-schema dependency and add manually (fix https://avd.aquasec.com/nvd/cve-2022-45688 )
=> #127 - Fix code scanning alert - json stack overflow vulnerability

pom.xml
update spring security to 6.1.0 to fix https://avd.aquasec.com/nvd/cve-2023-20862
=> #126 - Fix code scanning alert - Spring Security logout not clearing security context

.github/scripts/check-if-running-as-feasibility-user.sh, .github/workflows/ci.yml, Dockerfile
- create a user and group "feasibility" in the Dockerfile that runs the application instead of root user
- add a script that checks if java is really running as the user "feasibility" during github actions
=> #145 - Run Java in Docker Container as Non-Root

CHANGELOG.md, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFFhirSecurityContextProvider.java
- Declare FileInputStream in DSFFhirSecurityContextProvider in try-with-resources statement so that it is automatically closed afterward
=> Hotfix 3.1.2

src/main/resources/static/v3/api-docs/swagger.yaml
Assign unique operationIds for get summary result and get detailed obfuscated result endpoints
=> #165 - Duplicate operationId in swagger doc

pom.xml
- update hapi libs
- exclude guava dependency from hapi libs and add newer version to fix https://avd.aquasec.com/nvd/2023/cve-2023-2976/
=> #149 - Insecure temporary directory creation

.gitignore, pom.xml
Removed duplicate dependencies, added group ID to failsafe plugin and excluded vulnerable dependency commons-collections.
Also added result.log to .gitignore and removed duplicate .project entry.
=> Fix Problems in POM

README.md, docker-compose.yml, src/main/java/de/numcodex/feasibility_gui_backend/query/v3/QueryHandlerRestController.java, src/main/resources/application.yml, src/test/java/de/numcodex/feasibility_gui_backend/query/v3/QueryHandlerRestControllerIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/v3/QueryTemplateHandlerRestControllerIT.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/v3/TerminologyRestControllerIT.java, src/test/resources/application.yml
- add new variable app.privacy.threshold.sitesResult that defines the threshold a responding site must exceed in order to be configured responding in regard to the threshold for responding sites
=> #179 - Make restriction when site counts as answered configurable

pom.xml, src/main/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfig.java
Fixes https://avd.aquasec.com/nvd/2023/cve-2023-34035/
=> #188 - Update spring boot

pom.xml
Lock version of dependency `com.sun.xml.bind.jaxb-impl`, used by _aktin-client_  and _dsf-client_, to version `2.3.3` which is compatible to both.
=> Fix JAXB dependency conflict

src/main/resources/static/v3/api-docs/swagger.yaml
- correctly specify the list of context termcode hashes as requestBody instead of trying to submit it as a parameter in "body" (which is not supported)
=> #217 - Swaggerfile error

src/main/java/de/numcodex/feasibility_gui_backend/query/v3/QueryTemplateHandlerRestController.java
- correctly use the invalid terms list generated before
=> #222 - Fix code scanning alert - Unread local variable

src/main/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectBrokerClient.java
- add missing @Override annotation to DirectBrokerClient.getSiteName
=> #223 - Fix code scanning alert - Missing Override annotation

pom.xml
- update org.json:json to 20231013 to fix [CVE-2023-5072](https://avd.aquasec.com/nvd/2023/cve-2023-5072/)
=> #221 - Fix code scanning alert - parser confusion leads to OOM

src/main/java/de/numcodex/feasibility_gui_backend/terminology/TerminologyService.java, src/main/resources/application.yml, src/test/java/de/numcodex/feasibility_gui_backend/terminology/TerminologyServiceTest.java, src/test/resources/ontology/ui_profiles/CategoryA.json, src/test/resources/ontology/ui_profiles/CategoryB.json
A new application property _app.ontologyOrder_ is added and linked to the env variable _ONTOLOGY_ORDER_. It takes a comma-separated list of entries that predefine the order of the category list.
If the variable(s) should be named differently, just let me know
=> #219 - Make order of UI tree categories configurable via env var

src/main/resources/static/v3/api-docs/swagger.yaml
- add missing parameters to QueryListEntry
- fix "createdAt" parameter for QueryListEntry (is camelCase instead of snake_case)
=> #245 - Fix swagger documentation

README.md, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFFhirWebClientProvider.java, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFSpringConfig.java, src/main/resources/application.yml, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFFhirWebClientProviderTest.java
Add environment variable to enable request logging if needed.
closes #247
=> Disable DSFWebserviceClient requests logs by default

src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java, src/main/java/de/numcodex/feasibility_gui_backend/query/api/QueryListEntry.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v3/QueryHandlerRestController.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v3/QueryTemplateHandlerRestController.java, src/main/resources/static/v3/api-docs/swagger.yaml, src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceTest.java, src/test/java/de/numcodex/feasibility_gui_backend/query/v3/QueryHandlerRestControllerIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/v3/QueryTemplateHandlerRestControllerIT.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/v3/TerminologyRestControllerIT.java
* Modify the endpoints to retrieve query and query templates list. By default, always include validation of the queries (can be disabled via request parameter "skipValidation" (defaults to false)
* Remove /template/validate endpoint
:warning: We discussed whether or not this should lead to a new api version (v4), but it was decided against doing so, even if it technically is not correct. :warning:
=> #260 - Endpoint modification for template and savedqueries retrieval with activated validation

src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java, src/main/java/de/numcodex/feasibility_gui_backend/query/api/Query.java, src/main/java/de/numcodex/feasibility_gui_backend/query/api/QueryListEntry.java, src/main/java/de/numcodex/feasibility_gui_backend/query/api/QueryTemplate.java, src/main/java/de/numcodex/feasibility_gui_backend/query/api/StructuredQuery.java, src/main/java/de/numcodex/feasibility_gui_backend/query/api/ValidatedStructuredQuery.java, src/main/java/de/numcodex/feasibility_gui_backend/query/api/validation/StructuredQueryValidator.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v3/QueryHandlerRestController.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v3/QueryTemplateHandlerRestController.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/validation/TermCodeValidation.java, src/main/resources/de/numcodex/feasibility_gui_backend/query/api/validation/query-template-schema.json, src/main/resources/static/v3/api-docs/swagger.yaml, src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceTest.java, src/test/java/de/numcodex/feasibility_gui_backend/query/api/validation/QueryTemplateValidatorTest.java, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectBrokerClientCqlIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFFhirWebClientProviderTest.java, src/test/java/de/numcodex/feasibility_gui_backend/query/v3/QueryHandlerRestControllerIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/v3/QueryTemplateHandlerRestControllerIT.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/validation/TermCodeValidationTest.java
- Return invalid criteria (termcode/context) instead of just termcode
- Replace old /validate endpoint with the new one
- add swagger documentation for the endpoint
- When no invalid terms are found, return an empty array instead of omitting the parameter
- Don't include the invalid terms list in the structured query itself but create a new object ValidatedStructuredQuery, containing the original query and the list of invalid terms
- Add a new endpoint that takes a structured query and sends back the same query with additional invalidTerms if present
=> #258 - Add an endpoint that takes a structured query and validates it

src/test/java/de/numcodex/feasibility_gui_backend/query/broker/mock/MockBrokerClientIT.java
Increase the timeout to 15 sec when waiting for async response. Not sure if this REALLY fixes the problem since it did not occur all the time before. But with the increased timeout, the first test with github actions succeeded, and when I DEcreased the timeout locally, I occasionally run into the same error as github actions did. Not sure what else I can do to check here...
=> #276 - Error in MockBrokerClientIT

pom.xml
- update spring boot to 3.2.5
- remove manual netty-codec-http dependency inclusion since the vulnerable version is addressed in the spring boot update
- remove manual snakeyaml depdendency inclusion since it was also updated in spring boot in the meantime
=> #282 - Update Spring Boot

src/main/java/de/numcodex/feasibility_gui_backend/terminology/TerminologyService.java
- add missing lowercase conversion in TerminologyService.matchesQuery
=> #292 - OPS are not exhaustively searchable

.github/integration-test/docker-compose.yml, .github/scripts/post-test-query.sh, pom.xml, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectBrokerClientCqlIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFFhirWebClientProviderTest.java
* Update sq2cql to (currently) 0.3.0-rc.1 - update when final release is available!
* Update blaze, flare and keycloak in tests
=> #294 - Update sq2cql to version v0.3.0

pom.xml
- update undertow to 2.3.15.Final
- remove override of xnio dependencies since the new undertow version includes even newer ones
=> #327 - Update Undertow

src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptService.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsService.java
Please check if this solves the issue of no found results when an empty parameter for contexts, terminologies, kds-modules or criteria-sets is submitted
=> #330 - Empty filter lists lead to missing results

docker-entrypoint.sh
- add $JAVA_OPTS env variable to java call in docker-entrypoint.sh
=> #344 - Make JVM options in Dockerimage configurable

README.md
Because [the 'id' used in pom.xml is 'mii' ](https://github.com/medizininformatik-initiative/feasibility-backend/blob/develop/pom.xml#L298), it should also be used in the 'settings.xml'. Otherwise it would not be used for authentication.
=> Update README section 'Adding GitHub Package Repositories'

src/main/resources/static/v3/api-docs/swagger.yaml
- Change openapi version string to 3.1.0
- remove useless "todo" parts from info section
- remove empty "content" sections
- remove useless quotes and double quotes
=> #337 - Migrate swagger.yaml to openapi 3.1.0

pom.xml
While running some integration tests the following message appears in the logs:
```
Found multiple occurrences of org.json.JSONObject on the class path:
jar:file:/Users/jbellmann/.m2/repository/org/json/json/20231013/json-20231013.jar!/org/json/JSONObject.class
jar:file:/Users/jbellmann/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar!/org/json/JSONObject.class
You may wish to exclude one of them to ensure predictable runtime behavior
```
This PR excludes `com.vaadin.external.google:android-json` from `spring-boot-starter-test`.
=> Avoid multiple occurrences of org.json.JSONObject on the class path

src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java, src/main/java/de/numcodex/feasibility_gui_backend/query/api/Query.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v4/QueryHandlerRestController.java
- Add the totalNumberOfPatients from the saved query object back to the response when reading a query
- the demanded queryId from the issue is already present as "id" - so nothing to do here imho
=> #363 - Add "results" to GET query/{queryId} response

src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptService.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsService.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptServiceIT.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptServiceTest.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsServiceIT.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsServiceTest.java
- Change score modification to add an offset instead of multiplying when availability > 0
- remove the inner "must" part of the bool query when searchterm is empty
=> #376 - Allow Empty Search with filters

.github/integration-test/docker-compose.yml, .github/scripts/download-and-unpack-ontology.sh, .github/scripts/init-elasticsearch.sh, .github/scripts/post-elastic-test-queries.sh, .github/workflows/ci.yml
- add and enable elastic search in docker compose for github actions
- add some basic tests to check if elasticsearch is up and usable
=> #341 - Add elastic search to github integration tests

.github/workflows/ci.yml, pom.xml
- use wagon-maven-plugin for the download part of the ontology download/unpack process
- use copy-rename-plugin to move files
- use truezip plugin instead of unzip cmd (not available under windows)
- update jdk in ci.yml
=> #215 - use wagon maven plugin for ontology download

pom.xml, src/main/java/de/numcodex/feasibility_gui_backend/query/api/status/ValidationIssue.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/validation/StructuredQueryValidation.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/validation/StructuredQueryValidationTest.java
- update sq2cql to 0.6.0-SNAPSHOT
- check if timerestrictions are correct (before date is after afterdate)
- added new validation issue code to be returned to the gui. please check if this is ok this way and let me know if it should be something else (@juliangruendner @Shayan1375 @thkoehler11 )
=> #401 - Update sq2cql and validate time restrictions

.github/integration-test/docker-compose.yml, docker-compose.yml, src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptService.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptServiceIT.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsServiceIT.java
Add a slight delay (1s) in the test after uploading testdata to the elastic search container.
=> #334 -  Re-enable CodeableConceptServiceIT

src/main/java/de/numcodex/feasibility_gui_backend/dse/persistence/DseProfile.java, src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/Query.java, src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/QueryContent.java, src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/QueryDispatch.java, src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/QueryTemplate.java, src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/SavedQuery.java, src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/UserBlacklist.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/persistence/Context.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/persistence/ContextualizedTermCode.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/persistence/ContextualizedTermCodeToCriteriaSet.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/persistence/CriteriaSet.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/persistence/Mapping.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/persistence/TermCode.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/persistence/UiProfile.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/persistence/UiProfileContent.java, src/test/java/de/numcodex/feasibility_gui_backend/dse/DseServiceTest.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/TerminologyServiceTest.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptServiceIT.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/persistence/ContextTest.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/persistence/UiProfileContentTest.java
- Remove @Data and @EqualsAndHashCode annotations and replace them with @Getter @Setter @ToString (excluding lazily loaded variables) and custom equals and hashcode methods
- Change id datatype from int to Long in entity classes
=> #332 - Remove @Data annotation from jpa classes

src/main/resources/static/v3/api-docs/swagger.yaml
- added parameters for GET dse/profile-data
=> #431 - Parameters missing for dse profile data in swagger documentation

.github/scripts/post-elastic-test-queries.sh, src/main/java/de/numcodex/feasibility_gui_backend/terminology/api/CodeableConceptEntry.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptService.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/v4/CodeableConceptRestController.java, src/main/resources/static/v3/api-docs/swagger.yaml, src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptServiceIT.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptServiceTest.java, src/test/java/de/numcodex/feasibility_gui_backend/terminology/v4/CodeableConceptRestControllerIT.java
- Endpoint is changed to /codeable-concept/entry, expecting a list of ids as query parameter
- CodeableConceptEntry now included the id in the returned json
=> #433 - Change endpoint /codeable-concept/entry/{id} to allow for multiple ids

src/main/resources/static/v3/api-docs/swagger.yaml
- fix erroneous response example for criteria-profile-data
=> #442 - Faulty API Documentation

.github/workflows/ci.yml, pom.xml, src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/CodeableConceptService.java, src/main/java/de/numcodex/feasibility_gui_backend/terminology/es/TerminologyEsService.java, src/test/resources/de/numcodex/feasibility_gui_backend/terminology/es/codeable_concept.json, src/test/resources/de/numcodex/feasibility_gui_backend/terminology/es/ontology.json
**Warning** This will not work until [ontology generator issue 152](https://github.com/medizininformatik-initiative/fhir-ontology-generator/issues/152) is done and a new ontology is available for download. Otherwise tests will always fail.
And after the changes are done, this requires to set the new ontology tag here.
- Modify ontology search query to look in original field
- Modify codeable concept search query to look in original field
=> #446 - Search in original entry of display if no translations are available

src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java, src/main/java/de/numcodex/feasibility_gui_backend/query/api/status/QueryQuota.java, src/main/java/de/numcodex/feasibility_gui_backend/query/api/status/QueryQuotaEntry.java, src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/Query.java, src/main/java/de/numcodex/feasibility_gui_backend/query/persistence/QueryRepository.java, src/main/java/de/numcodex/feasibility_gui_backend/query/v4/QueryHandlerRestController.java, src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/v4/QueryHandlerRestControllerIT.java, src/test/resources/application.yml
- add endpoint /query/statistics to retrieve the amount of queries the user sent in the last 24h and last 168h
- Description was kinda sparse...so please let me know if you want it somehow different than I implemented it
- I assumed it should be "in the last 24h" and not "since midnight", same for the week, it's in the last 168h, not since monday 12am
=> #460 - provide count of "sent" queries

.github/workflows/ci.yml
Only allow tags starting with `v` followed by a valid [semantic version](https://semver.org/) to be released and only stable versions get the docker image `latest` tag attached.
=> Only Push Docker Image Tag 'latest' for Stable Versions

src/main/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManager.java, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/dsf/DSFQueryManagerTest.java
Fix rejection of task creation when having unversioned profile url of task match wrong structure definition version in DSF FHIR server.
=> Add Feasibility FHIR Resource Version to Profile URLs

src/main/java/de/numcodex/feasibility_gui_backend/query/v5/DataqueryHandlerRestController.java
=> #491 - Reading the crtdl part of a dataquery without cohortDefinition fails

src/main/java/de/numcodex/feasibility_gui_backend/query/v5/FeasibilityQueryHandlerRestController.java
Output is now:
Blacklisting user <userid> for exceeding quota without being poweruser. Allowed: 50 queries per P1W. The user posted 50 queries between 2025-04-28T15:20:20.650035424 and 2025-05-05T15:20:20.650035424
=> #499 - Improve log output when blacklisting user

pom.xml
com.nimbusds:oauth2-oidc-sdk:11.20.1 > 11.24
org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0 > 2.8.6 com.github.erosb:everit-json-schema:1.14.2 > 1.14.6 org.json:json:20240303 > 20250107
org.aktin:broker-client:1.5.0 > 1.5.1
org.apache.commons:commons-text:1.12.0 > 1.13.1
com.github.ben-manes.caffeine:caffeine:3.1.8 > 3.2.0 org.mockito:mockito-core:4.11.0 > 5.17.0
com.github.dasniko:testcontainers-keycloak:3.5.1 > 3.7.0 io.projectreactor:reactor-test:3.6.11 > 3.8.0-M3
org.jacoco:jacoco-maven-plugin:0.8.12 > 0.8.13
=> #507 - Update dependencies

README.md, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/NoOpInterceptor.java, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/direct/AsyncRequestException.java, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/direct/AsyncRequestExecutor.java, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectSpringConfig.java, src/main/java/de/numcodex/feasibility_gui_backend/query/broker/direct/FhirConnector.java, src/main/resources/application.yml, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectSpringConfigIT.java, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectSpringConfigTest.java, src/test/java/de/numcodex/feasibility_gui_backend/query/broker/direct/FhirConnectorTest.java
Added configuration property `broker.direct.cql.useAsyncRequestPattern` with default value true to support asynchronous request handling when the Direct Broker is using CQL queries. This enhancement improves performance by allowing non-blocking request processing, particularly useful for complex or long-running CQL queries.
The change is part of the broker client configuration and can be controlled via the environment variable
`BROKER_CLIENT_DIRECT_CQL_USE_ASYNC_REQUEST_PATTERN` when needed and defaults to `false` for staying compatible with deployments using HAPI based CQL-enabled FHIR servers which reject requests with unknown headers.
=> Implement FHIR Async Request Pattern for Direct Broker using CQL

src/main/java/de/numcodex/feasibility_gui_backend/query/broker/direct/DirectSpringConfig.java, src/main/resources/application.yml
- move direct broker cql settings to the same parent in application.yml
- remove unused flare readTimeout and connectTimeout
- move flare settings under direct broker config
=> #544 - Move cql config parameters in application yml
